# Generated by Django 4.1.3 on 2023-12-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
