# Generated by Django 4.1.3 on 2023-12-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_itemlist_upc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='oOrd',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='oRet',
        ),
    ]
