# Generated by Django 4.1.3 on 2023-12-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_itemlist_oord_remove_itemlist_oret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='mpq',
        ),
    ]
