# Generated by Django 4.1.3 on 2023-12-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_itemlist_mpq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordered',
            name='store',
        ),
    ]
